version: "2.1"

services:
    #---ASSET ENGINE---
    asset-engine:
      image: registry.service.pulsant.com/systems/asset-engine:${ASSET_ENGINE_VERSION}
      environment:
        - REDIS_URI_STRING=tcp://redis:6379
        - BLOCKER_THRESHOLD=${ASSET_ENGINE_BLOCKER_THRESHOLD}
      volumes:
        - ./var/files:/home/asset-engine/website/files
        - ./var/asset-engine/permissions.json:/home/asset-engine/website/site/section-permissions.json:ro
      networks:
        - frontend
        - backend-redis

    #---NGINX---
    nginx:
      image: nginx:${NGINX_VERSION}
      ports:
        - "${NGINX_PUBLISH_IP}:${NGINX_HTTP_PUBLISH}:80"
        - "${NGINX_PUBLISH_IP}:${NGINX_HTTPS_PUBLISH}:443"
      volumes:
        - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./config/nginx/ssl.conf:/etc/nginx/includes/ssl.conf:ro
        - ./var/certs:/etc/nginx/certs:ro
        - ./var/dhparam:/etc/nginx/dhparam:ro
      networks:
        - frontend

    #---REDIS---
    redis:
      image: redis:${REDIS_VERSION}
      container_name: redis
      networks:
        - backend-redis
networks:
  frontend: null
  backend-redis: null
